# Generated by Django 4.1.7 on 2023-03-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='amountingredient',
            name='unique_amountingredient_model',
        ),
        migrations.AddConstraint(
            model_name='amountingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_amountingredient_model'),
        ),
    ]
